name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.9"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.5.11"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: "true"
        cache-suffix: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: make install
      shell: bash

    - name: Check Python version and pip list
      run: |
        uv run --no-sync which python
        uv run --no-sync python --version
        uv pip list
      shell: bash
