name: Lint

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:  # manual button click

jobs:
  lint:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run linting
        run: |
          make check
