name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "README.md"
  workflow_dispatch: # manual button click

jobs:
  test-ubuntu:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"] # Test SDK Python version
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run unit tests
        run: |
          make test
